#  Python Print ASCII Values   ???

for i in range(1,1000):
	print("number of ascii value : ",i,"symbol of ascii value ","ascii valu0e : ",chr(i))
	
	
'''
output ===

number of ascii value :  1 symbol of ascii value  ascii valu0e :  
number of ascii value :  2 symbol of ascii value  ascii valu0e :  
number of ascii value :  3 symbol of ascii value  ascii valu0e :  
number of ascii value :  4 symbol of ascii value  ascii valu0e :  
number of ascii value :  5 symbol of ascii value  ascii valu0e :  
number of ascii value :  6 symbol of ascii value  ascii valu0e :  
number of ascii value :  7 symbol of ascii value  ascii valu0e :
number of ascii value :  8 symbol of ascii value  ascii valu0e :
number of ascii value :  9 symbol of ascii value  ascii valu0e :
number of ascii value :  10 symbol of ascii value  ascii valu0e :

number of ascii value :  11 symbol of ascii value  ascii valu0e :  
number of ascii value :  12 symbol of ascii value  ascii valu0e :  
number of ascii value :  13 symbol of ascii value  ascii valu0e :
number of ascii value :  14 symbol of ascii value  ascii valu0e :  
number of ascii value :  15 symbol of ascii value  ascii valu0e :  
number of ascii value :  16 symbol of ascii value  ascii valu0e :  
number of ascii value :  17 symbol of ascii value  ascii valu0e :  
number of ascii value :  18 symbol of ascii value  ascii valu0e :  
number of ascii value :  19 symbol of ascii value  ascii valu0e :  
number of ascii value :  20 symbol of ascii value  ascii valu0e :  
number of ascii value :  21 symbol of ascii value  ascii valu0e :  
number of ascii value :  22 symbol of ascii value  ascii valu0e :  
number of ascii value :  23 symbol of ascii value  ascii valu0e :  
number of ascii value :  24 symbol of ascii value  ascii valu0e :  
number of ascii value :  25 symbol of ascii value  ascii valu0e :  
number of ascii value :  26 symbol of ascii value  ascii valu0e :  
number of ascii value :  27 symbol of ascii value  ascii valu0e :  
number of ascii value :  28 symbol of ascii value  ascii valu0e :  
number of ascii value :  29 symbol of ascii value  ascii valu0e :  
number of ascii value :  30 symbol of ascii value  ascii valu0e :  
number of ascii value :  31 symbol of ascii value  ascii valu0e :  
number of ascii value :  32 symbol of ascii value  ascii valu0e :
number of ascii value :  33 symbol of ascii value  ascii valu0e :  !
number of ascii value :  34 symbol of ascii value  ascii valu0e :  "
number of ascii value :  35 symbol of ascii value  ascii valu0e :  #
number of ascii value :  36 symbol of ascii value  ascii valu0e :  $
number of ascii value :  37 symbol of ascii value  ascii valu0e :  %
number of ascii value :  38 symbol of ascii value  ascii valu0e :  &
number of ascii value :  39 symbol of ascii value  ascii valu0e :  '
number of ascii value :  40 symbol of ascii value  ascii valu0e :  (
number of ascii value :  41 symbol of ascii value  ascii valu0e :  )
number of ascii value :  42 symbol of ascii value  ascii valu0e :  *
number of ascii value :  43 symbol of ascii value  ascii valu0e :  +
number of ascii value :  44 symbol of ascii value  ascii valu0e :  ,
number of ascii value :  45 symbol of ascii value  ascii valu0e :  -
number of ascii value :  46 symbol of ascii value  ascii valu0e :  .
number of ascii value :  47 symbol of ascii value  ascii valu0e :  /
number of ascii value :  48 symbol of ascii value  ascii valu0e :  0
number of ascii value :  49 symbol of ascii value  ascii valu0e :  1
number of ascii value :  50 symbol of ascii value  ascii valu0e :  2
number of ascii value :  51 symbol of ascii value  ascii valu0e :  3
number of ascii value :  52 symbol of ascii value  ascii valu0e :  4
number of ascii value :  53 symbol of ascii value  ascii valu0e :  5
number of ascii value :  54 symbol of ascii value  ascii valu0e :  6
number of ascii value :  55 symbol of ascii value  ascii valu0e :  7
number of ascii value :  56 symbol of ascii value  ascii valu0e :  8
number of ascii value :  57 symbol of ascii value  ascii valu0e :  9
number of ascii value :  58 symbol of ascii value  ascii valu0e :  :
number of ascii value :  59 symbol of ascii value  ascii valu0e :  ;
number of ascii value :  60 symbol of ascii value  ascii valu0e :  <
number of ascii value :  61 symbol of ascii value  ascii valu0e :  =
number of ascii value :  62 symbol of ascii value  ascii valu0e :  >
number of ascii value :  63 symbol of ascii value  ascii valu0e :  ?
number of ascii value :  64 symbol of ascii value  ascii valu0e :  @
number of ascii value :  65 symbol of ascii value  ascii valu0e :  A
number of ascii value :  66 symbol of ascii value  ascii valu0e :  B
number of ascii value :  67 symbol of ascii value  ascii valu0e :  C
number of ascii value :  68 symbol of ascii value  ascii valu0e :  D
number of ascii value :  69 symbol of ascii value  ascii valu0e :  E
number of ascii value :  70 symbol of ascii value  ascii valu0e :  F
number of ascii value :  71 symbol of ascii value  ascii valu0e :  G
number of ascii value :  72 symbol of ascii value  ascii valu0e :  H
number of ascii value :  73 symbol of ascii value  ascii valu0e :  I
number of ascii value :  74 symbol of ascii value  ascii valu0e :  J
number of ascii value :  75 symbol of ascii value  ascii valu0e :  K
number of ascii value :  76 symbol of ascii value  ascii valu0e :  L
number of ascii value :  77 symbol of ascii value  ascii valu0e :  M
number of ascii value :  78 symbol of ascii value  ascii valu0e :  N
number of ascii value :  79 symbol of ascii value  ascii valu0e :  O
number of ascii value :  80 symbol of ascii value  ascii valu0e :  P
number of ascii value :  81 symbol of ascii value  ascii valu0e :  Q
number of ascii value :  82 symbol of ascii value  ascii valu0e :  R
number of ascii value :  83 symbol of ascii value  ascii valu0e :  S
number of ascii value :  84 symbol of ascii value  ascii valu0e :  T
number of ascii value :  85 symbol of ascii value  ascii valu0e :  U
number of ascii value :  86 symbol of ascii value  ascii valu0e :  V
number of ascii value :  87 symbol of ascii value  ascii valu0e :  W
number of ascii value :  88 symbol of ascii value  ascii valu0e :  X
number of ascii value :  89 symbol of ascii value  ascii valu0e :  Y
number of ascii value :  90 symbol of ascii value  ascii valu0e :  Z
number of ascii value :  91 symbol of ascii value  ascii valu0e :  [
number of ascii value :  92 symbol of ascii value  ascii valu0e :  \
number of ascii value :  93 symbol of ascii value  ascii valu0e :  ]
number of ascii value :  94 symbol of ascii value  ascii valu0e :  ^
number of ascii value :  95 symbol of ascii value  ascii valu0e :  _
number of ascii value :  96 symbol of ascii value  ascii valu0e :  `
number of ascii value :  97 symbol of ascii value  ascii valu0e :  a
number of ascii value :  98 symbol of ascii value  ascii valu0e :  b
number of ascii value :  99 symbol of ascii value  ascii valu0e :  c
number of ascii value :  100 symbol of ascii value  ascii valu0e :  d
number of ascii value :  101 symbol of ascii value  ascii valu0e :  e
number of ascii value :  102 symbol of ascii value  ascii valu0e :  f
number of ascii value :  103 symbol of ascii value  ascii valu0e :  g
number of ascii value :  104 symbol of ascii value  ascii valu0e :  h
number of ascii value :  105 symbol of ascii value  ascii valu0e :  i
number of ascii value :  106 symbol of ascii value  ascii valu0e :  j
number of ascii value :  107 symbol of ascii value  ascii valu0e :  k
number of ascii value :  108 symbol of ascii value  ascii valu0e :  l
number of ascii value :  109 symbol of ascii value  ascii valu0e :  m
number of ascii value :  110 symbol of ascii value  ascii valu0e :  n
number of ascii value :  111 symbol of ascii value  ascii valu0e :  o
number of ascii value :  112 symbol of ascii value  ascii valu0e :  p
number of ascii value :  113 symbol of ascii value  ascii valu0e :  q
number of ascii value :  114 symbol of ascii value  ascii valu0e :  r
number of ascii value :  115 symbol of ascii value  ascii valu0e :  s
number of ascii value :  116 symbol of ascii value  ascii valu0e :  t
number of ascii value :  117 symbol of ascii value  ascii valu0e :  u
number of ascii value :  118 symbol of ascii value  ascii valu0e :  v
number of ascii value :  119 symbol of ascii value  ascii valu0e :  w
number of ascii value :  120 symbol of ascii value  ascii valu0e :  x
number of ascii value :  121 symbol of ascii value  ascii valu0e :  y
number of ascii value :  122 symbol of ascii value  ascii valu0e :  z
number of ascii value :  123 symbol of ascii value  ascii valu0e :  {
number of ascii value :  124 symbol of ascii value  ascii valu0e :  |
number of ascii value :  125 symbol of ascii value  ascii valu0e :  }
number of ascii value :  126 symbol of ascii value  ascii valu0e :  ~
number of ascii value :  127 symbol of ascii value  ascii valu0e :  
number of ascii value :  128 symbol of ascii value  ascii valu0e :  
number of ascii value :  129 symbol of ascii value  ascii valu0e :  
number of ascii value :  130 symbol of ascii value  ascii valu0e :  
number of ascii value :  131 symbol of ascii value  ascii valu0e :  
number of ascii value :  132 symbol of ascii value  ascii valu0e :  
number of ascii value :  133 symbol of ascii value  ascii valu0e :  
number of ascii value :  134 symbol of ascii value  ascii valu0e :  
number of ascii value :  135 symbol of ascii value  ascii valu0e :  
number of ascii value :  136 symbol of ascii value  ascii valu0e :  
number of ascii value :  137 symbol of ascii value  ascii valu0e :  
number of ascii value :  138 symbol of ascii value  ascii valu0e :  
number of ascii value :  139 symbol of ascii value  ascii valu0e :  
number of ascii value :  140 symbol of ascii value  ascii valu0e :  
number of ascii value :  141 symbol of ascii value  ascii valu0e :  
number of ascii value :  142 symbol of ascii value  ascii valu0e :  
number of ascii value :  143 symbol of ascii value  ascii valu0e :  
number of ascii value :  144 symbol of ascii value  ascii valu0e :  
number of ascii value :  145 symbol of ascii value  ascii valu0e :  
number of ascii value :  146 symbol of ascii value  ascii valu0e :  
number of ascii value :  147 symbol of ascii value  ascii valu0e :  
number of ascii value :  148 symbol of ascii value  ascii valu0e :  
number of ascii value :  149 symbol of ascii value  ascii valu0e :  
number of ascii value :  150 symbol of ascii value  ascii valu0e :  
number of ascii value :  151 symbol of ascii value  ascii valu0e :  
number of ascii value :  152 symbol of ascii value  ascii valu0e :  
number of ascii value :  153 symbol of ascii value  ascii valu0e :  
number of ascii value :  154 symbol of ascii value  ascii valu0e :  
number of ascii value :  155 symbol of ascii value  ascii valu0e :  
number of ascii value :  156 symbol of ascii value  ascii valu0e :  
number of ascii value :  157 symbol of ascii value  ascii valu0e :  
number of ascii value :  158 symbol of ascii value  ascii valu0e :  
number of ascii value :  159 symbol of ascii value  ascii valu0e :  
number of ascii value :  160 symbol of ascii value  ascii valu0e :   
number of ascii value :  161 symbol of ascii value  ascii valu0e :  ¡
number of ascii value :  162 symbol of ascii value  ascii valu0e :  ¢
number of ascii value :  163 symbol of ascii value  ascii valu0e :  £
number of ascii value :  164 symbol of ascii value  ascii valu0e :  ¤
number of ascii value :  165 symbol of ascii value  ascii valu0e :  ¥
number of ascii value :  166 symbol of ascii value  ascii valu0e :  ¦
number of ascii value :  167 symbol of ascii value  ascii valu0e :  §
number of ascii value :  168 symbol of ascii value  ascii valu0e :  ¨
number of ascii value :  169 symbol of ascii value  ascii valu0e :  ©
number of ascii value :  170 symbol of ascii value  ascii valu0e :  ª
number of ascii value :  171 symbol of ascii value  ascii valu0e :  «
number of ascii value :  172 symbol of ascii value  ascii valu0e :  ¬
number of ascii value :  173 symbol of ascii value  ascii valu0e :  ­
number of ascii value :  174 symbol of ascii value  ascii valu0e :  ®
number of ascii value :  175 symbol of ascii value  ascii valu0e :  ¯
number of ascii value :  176 symbol of ascii value  ascii valu0e :  °
number of ascii value :  177 symbol of ascii value  ascii valu0e :  ±
number of ascii value :  178 symbol of ascii value  ascii valu0e :  ²
number of ascii value :  179 symbol of ascii value  ascii valu0e :  ³
number of ascii value :  180 symbol of ascii value  ascii valu0e :  ´
number of ascii value :  181 symbol of ascii value  ascii valu0e :  µ
number of ascii value :  182 symbol of ascii value  ascii valu0e :  ¶
number of ascii value :  183 symbol of ascii value  ascii valu0e :  ·
number of ascii value :  184 symbol of ascii value  ascii valu0e :  ¸
number of ascii value :  185 symbol of ascii value  ascii valu0e :  ¹
number of ascii value :  186 symbol of ascii value  ascii valu0e :  º
number of ascii value :  187 symbol of ascii value  ascii valu0e :  »
number of ascii value :  188 symbol of ascii value  ascii valu0e :  ¼
number of ascii value :  189 symbol of ascii value  ascii valu0e :  ½
number of ascii value :  190 symbol of ascii value  ascii valu0e :  ¾
number of ascii value :  191 symbol of ascii value  ascii valu0e :  ¿
number of ascii value :  192 symbol of ascii value  ascii valu0e :  À
number of ascii value :  193 symbol of ascii value  ascii valu0e :  Á
number of ascii value :  194 symbol of ascii value  ascii valu0e :  Â
number of ascii value :  195 symbol of ascii value  ascii valu0e :  Ã
number of ascii value :  196 symbol of ascii value  ascii valu0e :  Ä
number of ascii value :  197 symbol of ascii value  ascii valu0e :  Å
number of ascii value :  198 symbol of ascii value  ascii valu0e :  Æ
number of ascii value :  199 symbol of ascii value  ascii valu0e :  Ç
number of ascii value :  200 symbol of ascii value  ascii valu0e :  È
number of ascii value :  201 symbol of ascii value  ascii valu0e :  É
number of ascii value :  202 symbol of ascii value  ascii valu0e :  Ê
number of ascii value :  203 symbol of ascii value  ascii valu0e :  Ë
number of ascii value :  204 symbol of ascii value  ascii valu0e :  Ì
number of ascii value :  205 symbol of ascii value  ascii valu0e :  Í
number of ascii value :  206 symbol of ascii value  ascii valu0e :  Î
number of ascii value :  207 symbol of ascii value  ascii valu0e :  Ï
number of ascii value :  208 symbol of ascii value  ascii valu0e :  Ð
number of ascii value :  209 symbol of ascii value  ascii valu0e :  Ñ
number of ascii value :  210 symbol of ascii value  ascii valu0e :  Ò
number of ascii value :  211 symbol of ascii value  ascii valu0e :  Ó
number of ascii value :  212 symbol of ascii value  ascii valu0e :  Ô
number of ascii value :  213 symbol of ascii value  ascii valu0e :  Õ
number of ascii value :  214 symbol of ascii value  ascii valu0e :  Ö
number of ascii value :  215 symbol of ascii value  ascii valu0e :  ×
number of ascii value :  216 symbol of ascii value  ascii valu0e :  Ø
number of ascii value :  217 symbol of ascii value  ascii valu0e :  Ù
number of ascii value :  218 symbol of ascii value  ascii valu0e :  Ú
number of ascii value :  219 symbol of ascii value  ascii valu0e :  Û
number of ascii value :  220 symbol of ascii value  ascii valu0e :  Ü
number of ascii value :  221 symbol of ascii value  ascii valu0e :  Ý
number of ascii value :  222 symbol of ascii value  ascii valu0e :  Þ
number of ascii value :  223 symbol of ascii value  ascii valu0e :  ß
number of ascii value :  224 symbol of ascii value  ascii valu0e :  à
number of ascii value :  225 symbol of ascii value  ascii valu0e :  á
number of ascii value :  226 symbol of ascii value  ascii valu0e :  â
number of ascii value :  227 symbol of ascii value  ascii valu0e :  ã
number of ascii value :  228 symbol of ascii value  ascii valu0e :  ä
number of ascii value :  229 symbol of ascii value  ascii valu0e :  å
number of ascii value :  230 symbol of ascii value  ascii valu0e :  æ
number of ascii value :  231 symbol of ascii value  ascii valu0e :  ç
number of ascii value :  232 symbol of ascii value  ascii valu0e :  è
number of ascii value :  233 symbol of ascii value  ascii valu0e :  é
number of ascii value :  234 symbol of ascii value  ascii valu0e :  ê
number of ascii value :  235 symbol of ascii value  ascii valu0e :  ë
number of ascii value :  236 symbol of ascii value  ascii valu0e :  ì
number of ascii value :  237 symbol of ascii value  ascii valu0e :  í
number of ascii value :  238 symbol of ascii value  ascii valu0e :  î
number of ascii value :  239 symbol of ascii value  ascii valu0e :  ï
number of ascii value :  240 symbol of ascii value  ascii valu0e :  ð
number of ascii value :  241 symbol of ascii value  ascii valu0e :  ñ
number of ascii value :  242 symbol of ascii value  ascii valu0e :  ò
number of ascii value :  243 symbol of ascii value  ascii valu0e :  ó
number of ascii value :  244 symbol of ascii value  ascii valu0e :  ô
number of ascii value :  245 symbol of ascii value  ascii valu0e :  õ
number of ascii value :  246 symbol of ascii value  ascii valu0e :  ö
number of ascii value :  247 symbol of ascii value  ascii valu0e :  ÷
number of ascii value :  248 symbol of ascii value  ascii valu0e :  ø
number of ascii value :  249 symbol of ascii value  ascii valu0e :  ù
number of ascii value :  250 symbol of ascii value  ascii valu0e :  ú
number of ascii value :  251 symbol of ascii value  ascii valu0e :  û
number of ascii value :  252 symbol of ascii value  ascii valu0e :  ü
number of ascii value :  253 symbol of ascii value  ascii valu0e :  ý
number of ascii value :  254 symbol of ascii value  ascii valu0e :  þ
number of ascii value :  255 symbol of ascii value  ascii valu0e :  ÿ
number of ascii value :  256 symbol of ascii value  ascii valu0e :  Ā
number of ascii value :  257 symbol of ascii value  ascii valu0e :  ā
number of ascii value :  258 symbol of ascii value  ascii valu0e :  Ă
number of ascii value :  259 symbol of ascii value  ascii valu0e :  ă
number of ascii value :  260 symbol of ascii value  ascii valu0e :  Ą
number of ascii value :  261 symbol of ascii value  ascii valu0e :  ą
number of ascii value :  262 symbol of ascii value  ascii valu0e :  Ć
number of ascii value :  263 symbol of ascii value  ascii valu0e :  ć
number of ascii value :  264 symbol of ascii value  ascii valu0e :  Ĉ
number of ascii value :  265 symbol of ascii value  ascii valu0e :  ĉ
number of ascii value :  266 symbol of ascii value  ascii valu0e :  Ċ
number of ascii value :  267 symbol of ascii value  ascii valu0e :  ċ
number of ascii value :  268 symbol of ascii value  ascii valu0e :  Č
number of ascii value :  269 symbol of ascii value  ascii valu0e :  č
number of ascii value :  270 symbol of ascii value  ascii valu0e :  Ď
number of ascii value :  271 symbol of ascii value  ascii valu0e :  ď
number of ascii value :  272 symbol of ascii value  ascii valu0e :  Đ
number of ascii value :  273 symbol of ascii value  ascii valu0e :  đ
number of ascii value :  274 symbol of ascii value  ascii valu0e :  Ē
number of ascii value :  275 symbol of ascii value  ascii valu0e :  ē
number of ascii value :  276 symbol of ascii value  ascii valu0e :  Ĕ
number of ascii value :  277 symbol of ascii value  ascii valu0e :  ĕ
number of ascii value :  278 symbol of ascii value  ascii valu0e :  Ė
number of ascii value :  279 symbol of ascii value  ascii valu0e :  ė
number of ascii value :  280 symbol of ascii value  ascii valu0e :  Ę
number of ascii value :  281 symbol of ascii value  ascii valu0e :  ę
number of ascii value :  282 symbol of ascii value  ascii valu0e :  Ě
number of ascii value :  283 symbol of ascii value  ascii valu0e :  ě
number of ascii value :  284 symbol of ascii value  ascii valu0e :  Ĝ
number of ascii value :  285 symbol of ascii value  ascii valu0e :  ĝ
number of ascii value :  286 symbol of ascii value  ascii valu0e :  Ğ
number of ascii value :  287 symbol of ascii value  ascii valu0e :  ğ
number of ascii value :  288 symbol of ascii value  ascii valu0e :  Ġ
number of ascii value :  289 symbol of ascii value  ascii valu0e :  ġ
number of ascii value :  290 symbol of ascii value  ascii valu0e :  Ģ
number of ascii value :  291 symbol of ascii value  ascii valu0e :  ģ
number of ascii value :  292 symbol of ascii value  ascii valu0e :  Ĥ
number of ascii value :  293 symbol of ascii value  ascii valu0e :  ĥ
number of ascii value :  294 symbol of ascii value  ascii valu0e :  Ħ
number of ascii value :  295 symbol of ascii value  ascii valu0e :  ħ
number of ascii value :  296 symbol of ascii value  ascii valu0e :  Ĩ
number of ascii value :  297 symbol of ascii value  ascii valu0e :  ĩ
number of ascii value :  298 symbol of ascii value  ascii valu0e :  Ī
number of ascii value :  299 symbol of ascii value  ascii valu0e :  ī
number of ascii value :  300 symbol of ascii value  ascii valu0e :  Ĭ
number of ascii value :  301 symbol of ascii value  ascii valu0e :  ĭ
number of ascii value :  302 symbol of ascii value  ascii valu0e :  Į
number of ascii value :  303 symbol of ascii value  ascii valu0e :  į
number of ascii value :  304 symbol of ascii value  ascii valu0e :  İ
number of ascii value :  305 symbol of ascii value  ascii valu0e :  ı
number of ascii value :  306 symbol of ascii value  ascii valu0e :  Ĳ
number of ascii value :  307 symbol of ascii value  ascii valu0e :  ĳ
number of ascii value :  308 symbol of ascii value  ascii valu0e :  Ĵ
number of ascii value :  309 symbol of ascii value  ascii valu0e :  ĵ
number of ascii value :  310 symbol of ascii value  ascii valu0e :  Ķ
number of ascii value :  311 symbol of ascii value  ascii valu0e :  ķ
number of ascii value :  312 symbol of ascii value  ascii valu0e :  ĸ
number of ascii value :  313 symbol of ascii value  ascii valu0e :  Ĺ
number of ascii value :  314 symbol of ascii value  ascii valu0e :  ĺ
number of ascii value :  315 symbol of ascii value  ascii valu0e :  Ļ
number of ascii value :  316 symbol of ascii value  ascii valu0e :  ļ
number of ascii value :  317 symbol of ascii value  ascii valu0e :  Ľ
number of ascii value :  318 symbol of ascii value  ascii valu0e :  ľ
number of ascii value :  319 symbol of ascii value  ascii valu0e :  Ŀ
number of ascii value :  320 symbol of ascii value  ascii valu0e :  ŀ
number of ascii value :  321 symbol of ascii value  ascii valu0e :  Ł
number of ascii value :  322 symbol of ascii value  ascii valu0e :  ł
number of ascii value :  323 symbol of ascii value  ascii valu0e :  Ń
number of ascii value :  324 symbol of ascii value  ascii valu0e :  ń
number of ascii value :  325 symbol of ascii value  ascii valu0e :  Ņ
number of ascii value :  326 symbol of ascii value  ascii valu0e :  ņ
number of ascii value :  327 symbol of ascii value  ascii valu0e :  Ň
number of ascii value :  328 symbol of ascii value  ascii valu0e :  ň
number of ascii value :  329 symbol of ascii value  ascii valu0e :  ŉ
number of ascii value :  330 symbol of ascii value  ascii valu0e :  Ŋ
number of ascii value :  331 symbol of ascii value  ascii valu0e :  ŋ
number of ascii value :  332 symbol of ascii value  ascii valu0e :  Ō
number of ascii value :  333 symbol of ascii value  ascii valu0e :  ō
number of ascii value :  334 symbol of ascii value  ascii valu0e :  Ŏ
number of ascii value :  335 symbol of ascii value  ascii valu0e :  ŏ
number of ascii value :  336 symbol of ascii value  ascii valu0e :  Ő
number of ascii value :  337 symbol of ascii value  ascii valu0e :  ő
number of ascii value :  338 symbol of ascii value  ascii valu0e :  Œ
number of ascii value :  339 symbol of ascii value  ascii valu0e :  œ
number of ascii value :  340 symbol of ascii value  ascii valu0e :  Ŕ
number of ascii value :  341 symbol of ascii value  ascii valu0e :  ŕ
number of ascii value :  342 symbol of ascii value  ascii valu0e :  Ŗ
number of ascii value :  343 symbol of ascii value  ascii valu0e :  ŗ
number of ascii value :  344 symbol of ascii value  ascii valu0e :  Ř
number of ascii value :  345 symbol of ascii value  ascii valu0e :  ř
number of ascii value :  346 symbol of ascii value  ascii valu0e :  Ś
number of ascii value :  347 symbol of ascii value  ascii valu0e :  ś
number of ascii value :  348 symbol of ascii value  ascii valu0e :  Ŝ
number of ascii value :  349 symbol of ascii value  ascii valu0e :  ŝ
number of ascii value :  350 symbol of ascii value  ascii valu0e :  Ş
number of ascii value :  351 symbol of ascii value  ascii valu0e :  ş
number of ascii value :  352 symbol of ascii value  ascii valu0e :  Š
number of ascii value :  353 symbol of ascii value  ascii valu0e :  š
number of ascii value :  354 symbol of ascii value  ascii valu0e :  Ţ
number of ascii value :  355 symbol of ascii value  ascii valu0e :  ţ
number of ascii value :  356 symbol of ascii value  ascii valu0e :  Ť
number of ascii value :  357 symbol of ascii value  ascii valu0e :  ť
number of ascii value :  358 symbol of ascii value  ascii valu0e :  Ŧ
number of ascii value :  359 symbol of ascii value  ascii valu0e :  ŧ
number of ascii value :  360 symbol of ascii value  ascii valu0e :  Ũ
number of ascii value :  361 symbol of ascii value  ascii valu0e :  ũ
number of ascii value :  362 symbol of ascii value  ascii valu0e :  Ū
number of ascii value :  363 symbol of ascii value  ascii valu0e :  ū
number of ascii value :  364 symbol of ascii value  ascii valu0e :  Ŭ
number of ascii value :  365 symbol of ascii value  ascii valu0e :  ŭ
number of ascii value :  366 symbol of ascii value  ascii valu0e :  Ů
number of ascii value :  367 symbol of ascii value  ascii valu0e :  ů
number of ascii value :  368 symbol of ascii value  ascii valu0e :  Ű
number of ascii value :  369 symbol of ascii value  ascii valu0e :  ű
number of ascii value :  370 symbol of ascii value  ascii valu0e :  Ų
number of ascii value :  371 symbol of ascii value  ascii valu0e :  ų
number of ascii value :  372 symbol of ascii value  ascii valu0e :  Ŵ
number of ascii value :  373 symbol of ascii value  ascii valu0e :  ŵ
number of ascii value :  374 symbol of ascii value  ascii valu0e :  Ŷ
number of ascii value :  375 symbol of ascii value  ascii valu0e :  ŷ
number of ascii value :  376 symbol of ascii value  ascii valu0e :  Ÿ
number of ascii value :  377 symbol of ascii value  ascii valu0e :  Ź
number of ascii value :  378 symbol of ascii value  ascii valu0e :  ź
number of ascii value :  379 symbol of ascii value  ascii valu0e :  Ż
number of ascii value :  380 symbol of ascii value  ascii valu0e :  ż
number of ascii value :  381 symbol of ascii value  ascii valu0e :  Ž
number of ascii value :  382 symbol of ascii value  ascii valu0e :  ž
number of ascii value :  383 symbol of ascii value  ascii valu0e :  ſ
number of ascii value :  384 symbol of ascii value  ascii valu0e :  ƀ
number of ascii value :  385 symbol of ascii value  ascii valu0e :  Ɓ
number of ascii value :  386 symbol of ascii value  ascii valu0e :  Ƃ
number of ascii value :  387 symbol of ascii value  ascii valu0e :  ƃ
number of ascii value :  388 symbol of ascii value  ascii valu0e :  Ƅ
number of ascii value :  389 symbol of ascii value  ascii valu0e :  ƅ
number of ascii value :  390 symbol of ascii value  ascii valu0e :  Ɔ
number of ascii value :  391 symbol of ascii value  ascii valu0e :  Ƈ
number of ascii value :  392 symbol of ascii value  ascii valu0e :  ƈ
number of ascii value :  393 symbol of ascii value  ascii valu0e :  Ɖ
number of ascii value :  394 symbol of ascii value  ascii valu0e :  Ɗ
number of ascii value :  395 symbol of ascii value  ascii valu0e :  Ƌ
number of ascii value :  396 symbol of ascii value  ascii valu0e :  ƌ
number of ascii value :  397 symbol of ascii value  ascii valu0e :  ƍ
number of ascii value :  398 symbol of ascii value  ascii valu0e :  Ǝ
number of ascii value :  399 symbol of ascii value  ascii valu0e :  Ə
number of ascii value :  400 symbol of ascii value  ascii valu0e :  Ɛ
number of ascii value :  401 symbol of ascii value  ascii valu0e :  Ƒ
number of ascii value :  402 symbol of ascii value  ascii valu0e :  ƒ
number of ascii value :  403 symbol of ascii value  ascii valu0e :  Ɠ
number of ascii value :  404 symbol of ascii value  ascii valu0e :  Ɣ
number of ascii value :  405 symbol of ascii value  ascii valu0e :  ƕ
number of ascii value :  406 symbol of ascii value  ascii valu0e :  Ɩ
number of ascii value :  407 symbol of ascii value  ascii valu0e :  Ɨ
number of ascii value :  408 symbol of ascii value  ascii valu0e :  Ƙ
number of ascii value :  409 symbol of ascii value  ascii valu0e :  ƙ
number of ascii value :  410 symbol of ascii value  ascii valu0e :  ƚ
number of ascii value :  411 symbol of ascii value  ascii valu0e :  ƛ
number of ascii value :  412 symbol of ascii value  ascii valu0e :  Ɯ
number of ascii value :  413 symbol of ascii value  ascii valu0e :  Ɲ
number of ascii value :  414 symbol of ascii value  ascii valu0e :  ƞ
number of ascii value :  415 symbol of ascii value  ascii valu0e :  Ɵ
number of ascii value :  416 symbol of ascii value  ascii valu0e :  Ơ
number of ascii value :  417 symbol of ascii value  ascii valu0e :  ơ
number of ascii value :  418 symbol of ascii value  ascii valu0e :  Ƣ
number of ascii value :  419 symbol of ascii value  ascii valu0e :  ƣ
number of ascii value :  420 symbol of ascii value  ascii valu0e :  Ƥ
number of ascii value :  421 symbol of ascii value  ascii valu0e :  ƥ
number of ascii value :  422 symbol of ascii value  ascii valu0e :  Ʀ
number of ascii value :  423 symbol of ascii value  ascii valu0e :  Ƨ
number of ascii value :  424 symbol of ascii value  ascii valu0e :  ƨ
number of ascii value :  425 symbol of ascii value  ascii valu0e :  Ʃ
number of ascii value :  426 symbol of ascii value  ascii valu0e :  ƪ
number of ascii value :  427 symbol of ascii value  ascii valu0e :  ƫ
number of ascii value :  428 symbol of ascii value  ascii valu0e :  Ƭ
number of ascii value :  429 symbol of ascii value  ascii valu0e :  ƭ
number of ascii value :  430 symbol of ascii value  ascii valu0e :  Ʈ
number of ascii value :  431 symbol of ascii value  ascii valu0e :  Ư
number of ascii value :  432 symbol of ascii value  ascii valu0e :  ư
number of ascii value :  433 symbol of ascii value  ascii valu0e :  Ʊ
number of ascii value :  434 symbol of ascii value  ascii valu0e :  Ʋ
number of ascii value :  435 symbol of ascii value  ascii valu0e :  Ƴ
number of ascii value :  436 symbol of ascii value  ascii valu0e :  ƴ
number of ascii value :  437 symbol of ascii value  ascii valu0e :  Ƶ
number of ascii value :  438 symbol of ascii value  ascii valu0e :  ƶ
number of ascii value :  439 symbol of ascii value  ascii valu0e :  Ʒ
number of ascii value :  440 symbol of ascii value  ascii valu0e :  Ƹ
number of ascii value :  441 symbol of ascii value  ascii valu0e :  ƹ
number of ascii value :  442 symbol of ascii value  ascii valu0e :  ƺ
number of ascii value :  443 symbol of ascii value  ascii valu0e :  ƻ
number of ascii value :  444 symbol of ascii value  ascii valu0e :  Ƽ
number of ascii value :  445 symbol of ascii value  ascii valu0e :  ƽ
number of ascii value :  446 symbol of ascii value  ascii valu0e :  ƾ
number of ascii value :  447 symbol of ascii value  ascii valu0e :  ƿ
number of ascii value :  448 symbol of ascii value  ascii valu0e :  ǀ
number of ascii value :  449 symbol of ascii value  ascii valu0e :  ǁ
number of ascii value :  450 symbol of ascii value  ascii valu0e :  ǂ
number of ascii value :  451 symbol of ascii value  ascii valu0e :  ǃ
number of ascii value :  452 symbol of ascii value  ascii valu0e :  Ǆ
number of ascii value :  453 symbol of ascii value  ascii valu0e :  ǅ
number of ascii value :  454 symbol of ascii value  ascii valu0e :  ǆ
number of ascii value :  455 symbol of ascii value  ascii valu0e :  Ǉ
number of ascii value :  456 symbol of ascii value  ascii valu0e :  ǈ
number of ascii value :  457 symbol of ascii value  ascii valu0e :  ǉ
number of ascii value :  458 symbol of ascii value  ascii valu0e :  Ǌ
number of ascii value :  459 symbol of ascii value  ascii valu0e :  ǋ
number of ascii value :  460 symbol of ascii value  ascii valu0e :  ǌ
number of ascii value :  461 symbol of ascii value  ascii valu0e :  Ǎ
number of ascii value :  462 symbol of ascii value  ascii valu0e :  ǎ
number of ascii value :  463 symbol of ascii value  ascii valu0e :  Ǐ
number of ascii value :  464 symbol of ascii value  ascii valu0e :  ǐ
number of ascii value :  465 symbol of ascii value  ascii valu0e :  Ǒ
number of ascii value :  466 symbol of ascii value  ascii valu0e :  ǒ
number of ascii value :  467 symbol of ascii value  ascii valu0e :  Ǔ
number of ascii value :  468 symbol of ascii value  ascii valu0e :  ǔ
number of ascii value :  469 symbol of ascii value  ascii valu0e :  Ǖ
number of ascii value :  470 symbol of ascii value  ascii valu0e :  ǖ
number of ascii value :  471 symbol of ascii value  ascii valu0e :  Ǘ
number of ascii value :  472 symbol of ascii value  ascii valu0e :  ǘ
number of ascii value :  473 symbol of ascii value  ascii valu0e :  Ǚ
number of ascii value :  474 symbol of ascii value  ascii valu0e :  ǚ
number of ascii value :  475 symbol of ascii value  ascii valu0e :  Ǜ
number of ascii value :  476 symbol of ascii value  ascii valu0e :  ǜ
number of ascii value :  477 symbol of ascii value  ascii valu0e :  ǝ
number of ascii value :  478 symbol of ascii value  ascii valu0e :  Ǟ
number of ascii value :  479 symbol of ascii value  ascii valu0e :  ǟ
number of ascii value :  480 symbol of ascii value  ascii valu0e :  Ǡ
number of ascii value :  481 symbol of ascii value  ascii valu0e :  ǡ
number of ascii value :  482 symbol of ascii value  ascii valu0e :  Ǣ
number of ascii value :  483 symbol of ascii value  ascii valu0e :  ǣ
number of ascii value :  484 symbol of ascii value  ascii valu0e :  Ǥ
number of ascii value :  485 symbol of ascii value  ascii valu0e :  ǥ
number of ascii value :  486 symbol of ascii value  ascii valu0e :  Ǧ
number of ascii value :  487 symbol of ascii value  ascii valu0e :  ǧ
number of ascii value :  488 symbol of ascii value  ascii valu0e :  Ǩ
number of ascii value :  489 symbol of ascii value  ascii valu0e :  ǩ
number of ascii value :  490 symbol of ascii value  ascii valu0e :  Ǫ
number of ascii value :  491 symbol of ascii value  ascii valu0e :  ǫ
number of ascii value :  492 symbol of ascii value  ascii valu0e :  Ǭ
number of ascii value :  493 symbol of ascii value  ascii valu0e :  ǭ
number of ascii value :  494 symbol of ascii value  ascii valu0e :  Ǯ
number of ascii value :  495 symbol of ascii value  ascii valu0e :  ǯ
number of ascii value :  496 symbol of ascii value  ascii valu0e :  ǰ
number of ascii value :  497 symbol of ascii value  ascii valu0e :  Ǳ
number of ascii value :  498 symbol of ascii value  ascii valu0e :  ǲ
number of ascii value :  499 symbol of ascii value  ascii valu0e :  ǳ
number of ascii value :  500 symbol of ascii value  ascii valu0e :  Ǵ
number of ascii value :  501 symbol of ascii value  ascii valu0e :  ǵ
number of ascii value :  502 symbol of ascii value  ascii valu0e :  Ƕ
number of ascii value :  503 symbol of ascii value  ascii valu0e :  Ƿ
number of ascii value :  504 symbol of ascii value  ascii valu0e :  Ǹ
number of ascii value :  505 symbol of ascii value  ascii valu0e :  ǹ
number of ascii value :  506 symbol of ascii value  ascii valu0e :  Ǻ
number of ascii value :  507 symbol of ascii value  ascii valu0e :  ǻ
number of ascii value :  508 symbol of ascii value  ascii valu0e :  Ǽ
number of ascii value :  509 symbol of ascii value  ascii valu0e :  ǽ
number of ascii value :  510 symbol of ascii value  ascii valu0e :  Ǿ
number of ascii value :  511 symbol of ascii value  ascii valu0e :  ǿ
number of ascii value :  512 symbol of ascii value  ascii valu0e :  Ȁ
number of ascii value :  513 symbol of ascii value  ascii valu0e :  ȁ
number of ascii value :  514 symbol of ascii value  ascii valu0e :  Ȃ
number of ascii value :  515 symbol of ascii value  ascii valu0e :  ȃ
number of ascii value :  516 symbol of ascii value  ascii valu0e :  Ȅ
number of ascii value :  517 symbol of ascii value  ascii valu0e :  ȅ
number of ascii value :  518 symbol of ascii value  ascii valu0e :  Ȇ
number of ascii value :  519 symbol of ascii value  ascii valu0e :  ȇ
number of ascii value :  520 symbol of ascii value  ascii valu0e :  Ȉ
number of ascii value :  521 symbol of ascii value  ascii valu0e :  ȉ
number of ascii value :  522 symbol of ascii value  ascii valu0e :  Ȋ
number of ascii value :  523 symbol of ascii value  ascii valu0e :  ȋ
number of ascii value :  524 symbol of ascii value  ascii valu0e :  Ȍ
number of ascii value :  525 symbol of ascii value  ascii valu0e :  ȍ
number of ascii value :  526 symbol of ascii value  ascii valu0e :  Ȏ
number of ascii value :  527 symbol of ascii value  ascii valu0e :  ȏ
number of ascii value :  528 symbol of ascii value  ascii valu0e :  Ȑ
number of ascii value :  529 symbol of ascii value  ascii valu0e :  ȑ
number of ascii value :  530 symbol of ascii value  ascii valu0e :  Ȓ
number of ascii value :  531 symbol of ascii value  ascii valu0e :  ȓ
number of ascii value :  532 symbol of ascii value  ascii valu0e :  Ȕ
number of ascii value :  533 symbol of ascii value  ascii valu0e :  ȕ
number of ascii value :  534 symbol of ascii value  ascii valu0e :  Ȗ
number of ascii value :  535 symbol of ascii value  ascii valu0e :  ȗ
number of ascii value :  536 symbol of ascii value  ascii valu0e :  Ș
number of ascii value :  537 symbol of ascii value  ascii valu0e :  ș
number of ascii value :  538 symbol of ascii value  ascii valu0e :  Ț
number of ascii value :  539 symbol of ascii value  ascii valu0e :  ț
number of ascii value :  540 symbol of ascii value  ascii valu0e :  Ȝ
number of ascii value :  541 symbol of ascii value  ascii valu0e :  ȝ
number of ascii value :  542 symbol of ascii value  ascii valu0e :  Ȟ
number of ascii value :  543 symbol of ascii value  ascii valu0e :  ȟ
number of ascii value :  544 symbol of ascii value  ascii valu0e :  Ƞ
number of ascii value :  545 symbol of ascii value  ascii valu0e :  ȡ
number of ascii value :  546 symbol of ascii value  ascii valu0e :  Ȣ
number of ascii value :  547 symbol of ascii value  ascii valu0e :  ȣ
number of ascii value :  548 symbol of ascii value  ascii valu0e :  Ȥ
number of ascii value :  549 symbol of ascii value  ascii valu0e :  ȥ
number of ascii value :  550 symbol of ascii value  ascii valu0e :  Ȧ
number of ascii value :  551 symbol of ascii value  ascii valu0e :  ȧ
number of ascii value :  552 symbol of ascii value  ascii valu0e :  Ȩ
number of ascii value :  553 symbol of ascii value  ascii valu0e :  ȩ
number of ascii value :  554 symbol of ascii value  ascii valu0e :  Ȫ
number of ascii value :  555 symbol of ascii value  ascii valu0e :  ȫ
number of ascii value :  556 symbol of ascii value  ascii valu0e :  Ȭ
number of ascii value :  557 symbol of ascii value  ascii valu0e :  ȭ
number of ascii value :  558 symbol of ascii value  ascii valu0e :  Ȯ
number of ascii value :  559 symbol of ascii value  ascii valu0e :  ȯ
number of ascii value :  560 symbol of ascii value  ascii valu0e :  Ȱ
number of ascii value :  561 symbol of ascii value  ascii valu0e :  ȱ
number of ascii value :  562 symbol of ascii value  ascii valu0e :  Ȳ
number of ascii value :  563 symbol of ascii value  ascii valu0e :  ȳ
number of ascii value :  564 symbol of ascii value  ascii valu0e :  ȴ
number of ascii value :  565 symbol of ascii value  ascii valu0e :  ȵ
number of ascii value :  566 symbol of ascii value  ascii valu0e :  ȶ
number of ascii value :  567 symbol of ascii value  ascii valu0e :  ȷ
number of ascii value :  568 symbol of ascii value  ascii valu0e :  ȸ
number of ascii value :  569 symbol of ascii value  ascii valu0e :  ȹ
number of ascii value :  570 symbol of ascii value  ascii valu0e :  Ⱥ
number of ascii value :  571 symbol of ascii value  ascii valu0e :  Ȼ
number of ascii value :  572 symbol of ascii value  ascii valu0e :  ȼ
number of ascii value :  573 symbol of ascii value  ascii valu0e :  Ƚ
number of ascii value :  574 symbol of ascii value  ascii valu0e :  Ⱦ
number of ascii value :  575 symbol of ascii value  ascii valu0e :  ȿ
number of ascii value :  576 symbol of ascii value  ascii valu0e :  ɀ
number of ascii value :  577 symbol of ascii value  ascii valu0e :  Ɂ
number of ascii value :  578 symbol of ascii value  ascii valu0e :  ɂ
number of ascii value :  579 symbol of ascii value  ascii valu0e :  Ƀ
number of ascii value :  580 symbol of ascii value  ascii valu0e :  Ʉ
number of ascii value :  581 symbol of ascii value  ascii valu0e :  Ʌ
number of ascii value :  582 symbol of ascii value  ascii valu0e :  Ɇ
number of ascii value :  583 symbol of ascii value  ascii valu0e :  ɇ
number of ascii value :  584 symbol of ascii value  ascii valu0e :  Ɉ
number of ascii value :  585 symbol of ascii value  ascii valu0e :  ɉ
number of ascii value :  586 symbol of ascii value  ascii valu0e :  Ɋ
number of ascii value :  587 symbol of ascii value  ascii valu0e :  ɋ
number of ascii value :  588 symbol of ascii value  ascii valu0e :  Ɍ
number of ascii value :  589 symbol of ascii value  ascii valu0e :  ɍ
number of ascii value :  590 symbol of ascii value  ascii valu0e :  Ɏ
number of ascii value :  591 symbol of ascii value  ascii valu0e :  ɏ
number of ascii value :  592 symbol of ascii value  ascii valu0e :  ɐ
number of ascii value :  593 symbol of ascii value  ascii valu0e :  ɑ
number of ascii value :  594 symbol of ascii value  ascii valu0e :  ɒ
number of ascii value :  595 symbol of ascii value  ascii valu0e :  ɓ
number of ascii value :  596 symbol of ascii value  ascii valu0e :  ɔ
number of ascii value :  597 symbol of ascii value  ascii valu0e :  ɕ
number of ascii value :  598 symbol of ascii value  ascii valu0e :  ɖ
number of ascii value :  599 symbol of ascii value  ascii valu0e :  ɗ
number of ascii value :  600 symbol of ascii value  ascii valu0e :  ɘ
number of ascii value :  601 symbol of ascii value  ascii valu0e :  ə
number of ascii value :  602 symbol of ascii value  ascii valu0e :  ɚ
number of ascii value :  603 symbol of ascii value  ascii valu0e :  ɛ
number of ascii value :  604 symbol of ascii value  ascii valu0e :  ɜ
number of ascii value :  605 symbol of ascii value  ascii valu0e :  ɝ
number of ascii value :  606 symbol of ascii value  ascii valu0e :  ɞ
number of ascii value :  607 symbol of ascii value  ascii valu0e :  ɟ
number of ascii value :  608 symbol of ascii value  ascii valu0e :  ɠ
number of ascii value :  609 symbol of ascii value  ascii valu0e :  ɡ
number of ascii value :  610 symbol of ascii value  ascii valu0e :  ɢ
number of ascii value :  611 symbol of ascii value  ascii valu0e :  ɣ
number of ascii value :  612 symbol of ascii value  ascii valu0e :  ɤ
number of ascii value :  613 symbol of ascii value  ascii valu0e :  ɥ
number of ascii value :  614 symbol of ascii value  ascii valu0e :  ɦ
number of ascii value :  615 symbol of ascii value  ascii valu0e :  ɧ
number of ascii value :  616 symbol of ascii value  ascii valu0e :  ɨ
number of ascii value :  617 symbol of ascii value  ascii valu0e :  ɩ
number of ascii value :  618 symbol of ascii value  ascii valu0e :  ɪ
number of ascii value :  619 symbol of ascii value  ascii valu0e :  ɫ
number of ascii value :  620 symbol of ascii value  ascii valu0e :  ɬ
number of ascii value :  621 symbol of ascii value  ascii valu0e :  ɭ
number of ascii value :  622 symbol of ascii value  ascii valu0e :  ɮ
number of ascii value :  623 symbol of ascii value  ascii valu0e :  ɯ
number of ascii value :  624 symbol of ascii value  ascii valu0e :  ɰ
number of ascii value :  625 symbol of ascii value  ascii valu0e :  ɱ
number of ascii value :  626 symbol of ascii value  ascii valu0e :  ɲ
number of ascii value :  627 symbol of ascii value  ascii valu0e :  ɳ
number of ascii value :  628 symbol of ascii value  ascii valu0e :  ɴ
number of ascii value :  629 symbol of ascii value  ascii valu0e :  ɵ
number of ascii value :  630 symbol of ascii value  ascii valu0e :  ɶ
number of ascii value :  631 symbol of ascii value  ascii valu0e :  ɷ
number of ascii value :  632 symbol of ascii value  ascii valu0e :  ɸ
number of ascii value :  633 symbol of ascii value  ascii valu0e :  ɹ
number of ascii value :  634 symbol of ascii value  ascii valu0e :  ɺ
number of ascii value :  635 symbol of ascii value  ascii valu0e :  ɻ
number of ascii value :  636 symbol of ascii value  ascii valu0e :  ɼ
number of ascii value :  637 symbol of ascii value  ascii valu0e :  ɽ
number of ascii value :  638 symbol of ascii value  ascii valu0e :  ɾ
number of ascii value :  639 symbol of ascii value  ascii valu0e :  ɿ
number of ascii value :  640 symbol of ascii value  ascii valu0e :  ʀ
number of ascii value :  641 symbol of ascii value  ascii valu0e :  ʁ
number of ascii value :  642 symbol of ascii value  ascii valu0e :  ʂ
number of ascii value :  643 symbol of ascii value  ascii valu0e :  ʃ
number of ascii value :  644 symbol of ascii value  ascii valu0e :  ʄ
number of ascii value :  645 symbol of ascii value  ascii valu0e :  ʅ
number of ascii value :  646 symbol of ascii value  ascii valu0e :  ʆ
number of ascii value :  647 symbol of ascii value  ascii valu0e :  ʇ
number of ascii value :  648 symbol of ascii value  ascii valu0e :  ʈ
number of ascii value :  649 symbol of ascii value  ascii valu0e :  ʉ
number of ascii value :  650 symbol of ascii value  ascii valu0e :  ʊ
number of ascii value :  651 symbol of ascii value  ascii valu0e :  ʋ
number of ascii value :  652 symbol of ascii value  ascii valu0e :  ʌ
number of ascii value :  653 symbol of ascii value  ascii valu0e :  ʍ
number of ascii value :  654 symbol of ascii value  ascii valu0e :  ʎ
number of ascii value :  655 symbol of ascii value  ascii valu0e :  ʏ
number of ascii value :  656 symbol of ascii value  ascii valu0e :  ʐ
number of ascii value :  657 symbol of ascii value  ascii valu0e :  ʑ
number of ascii value :  658 symbol of ascii value  ascii valu0e :  ʒ
number of ascii value :  659 symbol of ascii value  ascii valu0e :  ʓ
number of ascii value :  660 symbol of ascii value  ascii valu0e :  ʔ
number of ascii value :  661 symbol of ascii value  ascii valu0e :  ʕ
number of ascii value :  662 symbol of ascii value  ascii valu0e :  ʖ
number of ascii value :  663 symbol of ascii value  ascii valu0e :  ʗ
number of ascii value :  664 symbol of ascii value  ascii valu0e :  ʘ
number of ascii value :  665 symbol of ascii value  ascii valu0e :  ʙ
number of ascii value :  666 symbol of ascii value  ascii valu0e :  ʚ
number of ascii value :  667 symbol of ascii value  ascii valu0e :  ʛ
number of ascii value :  668 symbol of ascii value  ascii valu0e :  ʜ
number of ascii value :  669 symbol of ascii value  ascii valu0e :  ʝ
number of ascii value :  670 symbol of ascii value  ascii valu0e :  ʞ
number of ascii value :  671 symbol of ascii value  ascii valu0e :  ʟ
number of ascii value :  672 symbol of ascii value  ascii valu0e :  ʠ
number of ascii value :  673 symbol of ascii value  ascii valu0e :  ʡ
number of ascii value :  674 symbol of ascii value  ascii valu0e :  ʢ
number of ascii value :  675 symbol of ascii value  ascii valu0e :  ʣ
number of ascii value :  676 symbol of ascii value  ascii valu0e :  ʤ
number of ascii value :  677 symbol of ascii value  ascii valu0e :  ʥ
number of ascii value :  678 symbol of ascii value  ascii valu0e :  ʦ
number of ascii value :  679 symbol of ascii value  ascii valu0e :  ʧ
number of ascii value :  680 symbol of ascii value  ascii valu0e :  ʨ
number of ascii value :  681 symbol of ascii value  ascii valu0e :  ʩ
number of ascii value :  682 symbol of ascii value  ascii valu0e :  ʪ
number of ascii value :  683 symbol of ascii value  ascii valu0e :  ʫ
number of ascii value :  684 symbol of ascii value  ascii valu0e :  ʬ
number of ascii value :  685 symbol of ascii value  ascii valu0e :  ʭ
number of ascii value :  686 symbol of ascii value  ascii valu0e :  ʮ
number of ascii value :  687 symbol of ascii value  ascii valu0e :  ʯ
number of ascii value :  688 symbol of ascii value  ascii valu0e :  ʰ
number of ascii value :  689 symbol of ascii value  ascii valu0e :  ʱ
number of ascii value :  690 symbol of ascii value  ascii valu0e :  ʲ
number of ascii value :  691 symbol of ascii value  ascii valu0e :  ʳ
number of ascii value :  692 symbol of ascii value  ascii valu0e :  ʴ
number of ascii value :  693 symbol of ascii value  ascii valu0e :  ʵ
number of ascii value :  694 symbol of ascii value  ascii valu0e :  ʶ
number of ascii value :  695 symbol of ascii value  ascii valu0e :  ʷ
number of ascii value :  696 symbol of ascii value  ascii valu0e :  ʸ
number of ascii value :  697 symbol of ascii value  ascii valu0e :  ʹ
number of ascii value :  698 symbol of ascii value  ascii valu0e :  ʺ
number of ascii value :  699 symbol of ascii value  ascii valu0e :  ʻ
number of ascii value :  700 symbol of ascii value  ascii valu0e :  ʼ
number of ascii value :  701 symbol of ascii value  ascii valu0e :  ʽ
number of ascii value :  702 symbol of ascii value  ascii valu0e :  ʾ
number of ascii value :  703 symbol of ascii value  ascii valu0e :  ʿ
number of ascii value :  704 symbol of ascii value  ascii valu0e :  ˀ
number of ascii value :  705 symbol of ascii value  ascii valu0e :  ˁ
number of ascii value :  706 symbol of ascii value  ascii valu0e :  ˂
number of ascii value :  707 symbol of ascii value  ascii valu0e :  ˃
number of ascii value :  708 symbol of ascii value  ascii valu0e :  ˄
number of ascii value :  709 symbol of ascii value  ascii valu0e :  ˅
number of ascii value :  710 symbol of ascii value  ascii valu0e :  ˆ
number of ascii value :  711 symbol of ascii value  ascii valu0e :  ˇ
number of ascii value :  712 symbol of ascii value  ascii valu0e :  ˈ
number of ascii value :  713 symbol of ascii value  ascii valu0e :  ˉ
number of ascii value :  714 symbol of ascii value  ascii valu0e :  ˊ
number of ascii value :  715 symbol of ascii value  ascii valu0e :  ˋ
number of ascii value :  716 symbol of ascii value  ascii valu0e :  ˌ
number of ascii value :  717 symbol of ascii value  ascii valu0e :  ˍ
number of ascii value :  718 symbol of ascii value  ascii valu0e :  ˎ
number of ascii value :  719 symbol of ascii value  ascii valu0e :  ˏ
number of ascii value :  720 symbol of ascii value  ascii valu0e :  ː
number of ascii value :  721 symbol of ascii value  ascii valu0e :  ˑ
number of ascii value :  722 symbol of ascii value  ascii valu0e :  ˒
number of ascii value :  723 symbol of ascii value  ascii valu0e :  ˓
number of ascii value :  724 symbol of ascii value  ascii valu0e :  ˔
number of ascii value :  725 symbol of ascii value  ascii valu0e :  ˕
number of ascii value :  726 symbol of ascii value  ascii valu0e :  ˖
number of ascii value :  727 symbol of ascii value  ascii valu0e :  ˗
number of ascii value :  728 symbol of ascii value  ascii valu0e :  ˘
number of ascii value :  729 symbol of ascii value  ascii valu0e :  ˙
number of ascii value :  730 symbol of ascii value  ascii valu0e :  ˚
number of ascii value :  731 symbol of ascii value  ascii valu0e :  ˛
number of ascii value :  732 symbol of ascii value  ascii valu0e :  ˜
number of ascii value :  733 symbol of ascii value  ascii valu0e :  ˝
number of ascii value :  734 symbol of ascii value  ascii valu0e :  ˞
number of ascii value :  735 symbol of ascii value  ascii valu0e :  ˟
number of ascii value :  736 symbol of ascii value  ascii valu0e :  ˠ
number of ascii value :  737 symbol of ascii value  ascii valu0e :  ˡ
number of ascii value :  738 symbol of ascii value  ascii valu0e :  ˢ
number of ascii value :  739 symbol of ascii value  ascii valu0e :  ˣ
number of ascii value :  740 symbol of ascii value  ascii valu0e :  ˤ
number of ascii value :  741 symbol of ascii value  ascii valu0e :  ˥
number of ascii value :  742 symbol of ascii value  ascii valu0e :  ˦
number of ascii value :  743 symbol of ascii value  ascii valu0e :  ˧
number of ascii value :  744 symbol of ascii value  ascii valu0e :  ˨
number of ascii value :  745 symbol of ascii value  ascii valu0e :  ˩
number of ascii value :  746 symbol of ascii value  ascii valu0e :  ˪
number of ascii value :  747 symbol of ascii value  ascii valu0e :  ˫
number of ascii value :  748 symbol of ascii value  ascii valu0e :  ˬ
number of ascii value :  749 symbol of ascii value  ascii valu0e :  ˭
number of ascii value :  750 symbol of ascii value  ascii valu0e :  ˮ
number of ascii value :  751 symbol of ascii value  ascii valu0e :  ˯
number of ascii value :  752 symbol of ascii value  ascii valu0e :  ˰
number of ascii value :  753 symbol of ascii value  ascii valu0e :  ˱
number of ascii value :  754 symbol of ascii value  ascii valu0e :  ˲
number of ascii value :  755 symbol of ascii value  ascii valu0e :  ˳
number of ascii value :  756 symbol of ascii value  ascii valu0e :  ˴
number of ascii value :  757 symbol of ascii value  ascii valu0e :  ˵
number of ascii value :  758 symbol of ascii value  ascii valu0e :  ˶
number of ascii value :  759 symbol of ascii value  ascii valu0e :  ˷
number of ascii value :  760 symbol of ascii value  ascii valu0e :  ˸
number of ascii value :  761 symbol of ascii value  ascii valu0e :  ˹
number of ascii value :  762 symbol of ascii value  ascii valu0e :  ˺
number of ascii value :  763 symbol of ascii value  ascii valu0e :  ˻
number of ascii value :  764 symbol of ascii value  ascii valu0e :  ˼
number of ascii value :  765 symbol of ascii value  ascii valu0e :  ˽
number of ascii value :  766 symbol of ascii value  ascii valu0e :  ˾
number of ascii value :  767 symbol of ascii value  ascii valu0e :  ˿
number of ascii value :  768 symbol of ascii value  ascii valu0e :  ̀
number of ascii value :  769 symbol of ascii value  ascii valu0e :  ́
number of ascii value :  770 symbol of ascii value  ascii valu0e :  ̂
number of ascii value :  771 symbol of ascii value  ascii valu0e :  ̃
number of ascii value :  772 symbol of ascii value  ascii valu0e :  ̄
number of ascii value :  773 symbol of ascii value  ascii valu0e :  ̅
number of ascii value :  774 symbol of ascii value  ascii valu0e :  ̆
number of ascii value :  775 symbol of ascii value  ascii valu0e :  ̇
number of ascii value :  776 symbol of ascii value  ascii valu0e :  ̈
number of ascii value :  777 symbol of ascii value  ascii valu0e :  ̉
number of ascii value :  778 symbol of ascii value  ascii valu0e :  ̊
number of ascii value :  779 symbol of ascii value  ascii valu0e :  ̋
number of ascii value :  780 symbol of ascii value  ascii valu0e :  ̌
number of ascii value :  781 symbol of ascii value  ascii valu0e :  ̍
number of ascii value :  782 symbol of ascii value  ascii valu0e :  ̎
number of ascii value :  783 symbol of ascii value  ascii valu0e :  ̏
number of ascii value :  784 symbol of ascii value  ascii valu0e :  ̐
number of ascii value :  785 symbol of ascii value  ascii valu0e :  ̑
number of ascii value :  786 symbol of ascii value  ascii valu0e :  ̒
number of ascii value :  787 symbol of ascii value  ascii valu0e :  ̓
number of ascii value :  788 symbol of ascii value  ascii valu0e :  ̔
number of ascii value :  789 symbol of ascii value  ascii valu0e :  ̕
number of ascii value :  790 symbol of ascii value  ascii valu0e :  ̖
number of ascii value :  791 symbol of ascii value  ascii valu0e :  ̗
number of ascii value :  792 symbol of ascii value  ascii valu0e :  ̘
number of ascii value :  793 symbol of ascii value  ascii valu0e :  ̙
number of ascii value :  794 symbol of ascii value  ascii valu0e :  ̚
number of ascii value :  795 symbol of ascii value  ascii valu0e :  ̛
number of ascii value :  796 symbol of ascii value  ascii valu0e :  ̜
number of ascii value :  797 symbol of ascii value  ascii valu0e :  ̝
number of ascii value :  798 symbol of ascii value  ascii valu0e :  ̞
number of ascii value :  799 symbol of ascii value  ascii valu0e :  ̟
number of ascii value :  800 symbol of ascii value  ascii valu0e :  ̠
number of ascii value :  801 symbol of ascii value  ascii valu0e :  ̡
number of ascii value :  802 symbol of ascii value  ascii valu0e :  ̢
number of ascii value :  803 symbol of ascii value  ascii valu0e :  ̣
number of ascii value :  804 symbol of ascii value  ascii valu0e :  ̤
number of ascii value :  805 symbol of ascii value  ascii valu0e :  ̥
number of ascii value :  806 symbol of ascii value  ascii valu0e :  ̦
number of ascii value :  807 symbol of ascii value  ascii valu0e :  ̧
number of ascii value :  808 symbol of ascii value  ascii valu0e :  ̨
number of ascii value :  809 symbol of ascii value  ascii valu0e :  ̩
number of ascii value :  810 symbol of ascii value  ascii valu0e :  ̪
number of ascii value :  811 symbol of ascii value  ascii valu0e :  ̫
number of ascii value :  812 symbol of ascii value  ascii valu0e :  ̬
number of ascii value :  813 symbol of ascii value  ascii valu0e :  ̭
number of ascii value :  814 symbol of ascii value  ascii valu0e :  ̮
number of ascii value :  815 symbol of ascii value  ascii valu0e :  ̯
number of ascii value :  816 symbol of ascii value  ascii valu0e :  ̰
number of ascii value :  817 symbol of ascii value  ascii valu0e :  ̱
number of ascii value :  818 symbol of ascii value  ascii valu0e :  ̲
number of ascii value :  819 symbol of ascii value  ascii valu0e :  ̳
number of ascii value :  820 symbol of ascii value  ascii valu0e :  ̴
number of ascii value :  821 symbol of ascii value  ascii valu0e :  ̵
number of ascii value :  822 symbol of ascii value  ascii valu0e :  ̶
number of ascii value :  823 symbol of ascii value  ascii valu0e :  ̷
number of ascii value :  824 symbol of ascii value  ascii valu0e :  ̸
number of ascii value :  825 symbol of ascii value  ascii valu0e :  ̹
number of ascii value :  826 symbol of ascii value  ascii valu0e :  ̺
number of ascii value :  827 symbol of ascii value  ascii valu0e :  ̻
number of ascii value :  828 symbol of ascii value  ascii valu0e :  ̼
number of ascii value :  829 symbol of ascii value  ascii valu0e :  ̽
number of ascii value :  830 symbol of ascii value  ascii valu0e :  ̾
number of ascii value :  831 symbol of ascii value  ascii valu0e :  ̿
number of ascii value :  832 symbol of ascii value  ascii valu0e :  ̀
number of ascii value :  833 symbol of ascii value  ascii valu0e :  ́
number of ascii value :  834 symbol of ascii value  ascii valu0e :  ͂
number of ascii value :  835 symbol of ascii value  ascii valu0e :  ̓
number of ascii value :  836 symbol of ascii value  ascii valu0e :  ̈́
number of ascii value :  837 symbol of ascii value  ascii valu0e :  ͅ
number of ascii value :  838 symbol of ascii value  ascii valu0e :  ͆
number of ascii value :  839 symbol of ascii value  ascii valu0e :  ͇
number of ascii value :  840 symbol of ascii value  ascii valu0e :  ͈
number of ascii value :  841 symbol of ascii value  ascii valu0e :  ͉
number of ascii value :  842 symbol of ascii value  ascii valu0e :  ͊
number of ascii value :  843 symbol of ascii value  ascii valu0e :  ͋
number of ascii value :  844 symbol of ascii value  ascii valu0e :  ͌
number of ascii value :  845 symbol of ascii value  ascii valu0e :  ͍
number of ascii value :  846 symbol of ascii value  ascii valu0e :  ͎
number of ascii value :  847 symbol of ascii value  ascii valu0e :  ͏
number of ascii value :  848 symbol of ascii value  ascii valu0e :  ͐
number of ascii value :  849 symbol of ascii value  ascii valu0e :  ͑
number of ascii value :  850 symbol of ascii value  ascii valu0e :  ͒
number of ascii value :  851 symbol of ascii value  ascii valu0e :  ͓
number of ascii value :  852 symbol of ascii value  ascii valu0e :  ͔
number of ascii value :  853 symbol of ascii value  ascii valu0e :  ͕
number of ascii value :  854 symbol of ascii value  ascii valu0e :  ͖
number of ascii value :  855 symbol of ascii value  ascii valu0e :  ͗
number of ascii value :  856 symbol of ascii value  ascii valu0e :  ͘
number of ascii value :  857 symbol of ascii value  ascii valu0e :  ͙
number of ascii value :  858 symbol of ascii value  ascii valu0e :  ͚
number of ascii value :  859 symbol of ascii value  ascii valu0e :  ͛
number of ascii value :  860 symbol of ascii value  ascii valu0e :  ͜
number of ascii value :  861 symbol of ascii value  ascii valu0e :  ͝
number of ascii value :  862 symbol of ascii value  ascii valu0e :  ͞
number of ascii value :  863 symbol of ascii value  ascii valu0e :  ͟
number of ascii value :  864 symbol of ascii value  ascii valu0e :  ͠
number of ascii value :  865 symbol of ascii value  ascii valu0e :  ͡
number of ascii value :  866 symbol of ascii value  ascii valu0e :  ͢
number of ascii value :  867 symbol of ascii value  ascii valu0e :  ͣ
number of ascii value :  868 symbol of ascii value  ascii valu0e :  ͤ
number of ascii value :  869 symbol of ascii value  ascii valu0e :  ͥ
number of ascii value :  870 symbol of ascii value  ascii valu0e :  ͦ
number of ascii value :  871 symbol of ascii value  ascii valu0e :  ͧ
number of ascii value :  872 symbol of ascii value  ascii valu0e :  ͨ
number of ascii value :  873 symbol of ascii value  ascii valu0e :  ͩ
number of ascii value :  874 symbol of ascii value  ascii valu0e :  ͪ
number of ascii value :  875 symbol of ascii value  ascii valu0e :  ͫ
number of ascii value :  876 symbol of ascii value  ascii valu0e :  ͬ
number of ascii value :  877 symbol of ascii value  ascii valu0e :  ͭ
number of ascii value :  878 symbol of ascii value  ascii valu0e :  ͮ
number of ascii value :  879 symbol of ascii value  ascii valu0e :  ͯ
number of ascii value :  880 symbol of ascii value  ascii valu0e :  Ͱ
number of ascii value :  881 symbol of ascii value  ascii valu0e :  ͱ
number of ascii value :  882 symbol of ascii value  ascii valu0e :  Ͳ
number of ascii value :  883 symbol of ascii value  ascii valu0e :  ͳ
number of ascii value :  884 symbol of ascii value  ascii valu0e :  ʹ
number of ascii value :  885 symbol of ascii value  ascii valu0e :  ͵
number of ascii value :  886 symbol of ascii value  ascii valu0e :  Ͷ
number of ascii value :  887 symbol of ascii value  ascii valu0e :  ͷ
number of ascii value :  888 symbol of ascii value  ascii valu0e :  ͸
number of ascii value :  889 symbol of ascii value  ascii valu0e :  ͹
number of ascii value :  890 symbol of ascii value  ascii valu0e :  ͺ
number of ascii value :  891 symbol of ascii value  ascii valu0e :  ͻ
number of ascii value :  892 symbol of ascii value  ascii valu0e :  ͼ
number of ascii value :  893 symbol of ascii value  ascii valu0e :  ͽ
number of ascii value :  894 symbol of ascii value  ascii valu0e :  ;
number of ascii value :  895 symbol of ascii value  ascii valu0e :  Ϳ
number of ascii value :  896 symbol of ascii value  ascii valu0e :  ΀
number of ascii value :  897 symbol of ascii value  ascii valu0e :  ΁
number of ascii value :  898 symbol of ascii value  ascii valu0e :  ΂
number of ascii value :  899 symbol of ascii value  ascii valu0e :  ΃
number of ascii value :  900 symbol of ascii value  ascii valu0e :  ΄
number of ascii value :  901 symbol of ascii value  ascii valu0e :  ΅
number of ascii value :  902 symbol of ascii value  ascii valu0e :  Ά
number of ascii value :  903 symbol of ascii value  ascii valu0e :  ·
number of ascii value :  904 symbol of ascii value  ascii valu0e :  Έ
number of ascii value :  905 symbol of ascii value  ascii valu0e :  Ή
number of ascii value :  906 symbol of ascii value  ascii valu0e :  Ί
number of ascii value :  907 symbol of ascii value  ascii valu0e :  ΋
number of ascii value :  908 symbol of ascii value  ascii valu0e :  Ό
number of ascii value :  909 symbol of ascii value  ascii valu0e :  ΍
number of ascii value :  910 symbol of ascii value  ascii valu0e :  Ύ
number of ascii value :  911 symbol of ascii value  ascii valu0e :  Ώ
number of ascii value :  912 symbol of ascii value  ascii valu0e :  ΐ
number of ascii value :  913 symbol of ascii value  ascii valu0e :  Α
number of ascii value :  914 symbol of ascii value  ascii valu0e :  Β
number of ascii value :  915 symbol of ascii value  ascii valu0e :  Γ
number of ascii value :  916 symbol of ascii value  ascii valu0e :  Δ
number of ascii value :  917 symbol of ascii value  ascii valu0e :  Ε
number of ascii value :  918 symbol of ascii value  ascii valu0e :  Ζ
number of ascii value :  919 symbol of ascii value  ascii valu0e :  Η
number of ascii value :  920 symbol of ascii value  ascii valu0e :  Θ
number of ascii value :  921 symbol of ascii value  ascii valu0e :  Ι
number of ascii value :  922 symbol of ascii value  ascii valu0e :  Κ
number of ascii value :  923 symbol of ascii value  ascii valu0e :  Λ
number of ascii value :  924 symbol of ascii value  ascii valu0e :  Μ
number of ascii value :  925 symbol of ascii value  ascii valu0e :  Ν
number of ascii value :  926 symbol of ascii value  ascii valu0e :  Ξ
number of ascii value :  927 symbol of ascii value  ascii valu0e :  Ο
number of ascii value :  928 symbol of ascii value  ascii valu0e :  Π
number of ascii value :  929 symbol of ascii value  ascii valu0e :  Ρ
number of ascii value :  930 symbol of ascii value  ascii valu0e :  ΢
number of ascii value :  931 symbol of ascii value  ascii valu0e :  Σ
number of ascii value :  932 symbol of ascii value  ascii valu0e :  Τ
number of ascii value :  933 symbol of ascii value  ascii valu0e :  Υ
number of ascii value :  934 symbol of ascii value  ascii valu0e :  Φ
number of ascii value :  935 symbol of ascii value  ascii valu0e :  Χ
number of ascii value :  936 symbol of ascii value  ascii valu0e :  Ψ
number of ascii value :  937 symbol of ascii value  ascii valu0e :  Ω
number of ascii value :  938 symbol of ascii value  ascii valu0e :  Ϊ
number of ascii value :  939 symbol of ascii value  ascii valu0e :  Ϋ
number of ascii value :  940 symbol of ascii value  ascii valu0e :  ά
number of ascii value :  941 symbol of ascii value  ascii valu0e :  έ
number of ascii value :  942 symbol of ascii value  ascii valu0e :  ή
number of ascii value :  943 symbol of ascii value  ascii valu0e :  ί
number of ascii value :  944 symbol of ascii value  ascii valu0e :  ΰ
number of ascii value :  945 symbol of ascii value  ascii valu0e :  α
number of ascii value :  946 symbol of ascii value  ascii valu0e :  β
number of ascii value :  947 symbol of ascii value  ascii valu0e :  γ
number of ascii value :  948 symbol of ascii value  ascii valu0e :  δ
number of ascii value :  949 symbol of ascii value  ascii valu0e :  ε
number of ascii value :  950 symbol of ascii value  ascii valu0e :  ζ
number of ascii value :  951 symbol of ascii value  ascii valu0e :  η
number of ascii value :  952 symbol of ascii value  ascii valu0e :  θ
number of ascii value :  953 symbol of ascii value  ascii valu0e :  ι
number of ascii value :  954 symbol of ascii value  ascii valu0e :  κ
number of ascii value :  955 symbol of ascii value  ascii valu0e :  λ
number of ascii value :  956 symbol of ascii value  ascii valu0e :  μ
number of ascii value :  957 symbol of ascii value  ascii valu0e :  ν
number of ascii value :  958 symbol of ascii value  ascii valu0e :  ξ
number of ascii value :  959 symbol of ascii value  ascii valu0e :  ο
number of ascii value :  960 symbol of ascii value  ascii valu0e :  π
number of ascii value :  961 symbol of ascii value  ascii valu0e :  ρ
number of ascii value :  962 symbol of ascii value  ascii valu0e :  ς
number of ascii value :  963 symbol of ascii value  ascii valu0e :  σ
number of ascii value :  964 symbol of ascii value  ascii valu0e :  τ
number of ascii value :  965 symbol of ascii value  ascii valu0e :  υ
number of ascii value :  966 symbol of ascii value  ascii valu0e :  φ
number of ascii value :  967 symbol of ascii value  ascii valu0e :  χ
number of ascii value :  968 symbol of ascii value  ascii valu0e :  ψ
number of ascii value :  969 symbol of ascii value  ascii valu0e :  ω
number of ascii value :  970 symbol of ascii value  ascii valu0e :  ϊ
number of ascii value :  971 symbol of ascii value  ascii valu0e :  ϋ
number of ascii value :  972 symbol of ascii value  ascii valu0e :  ό
number of ascii value :  973 symbol of ascii value  ascii valu0e :  ύ
number of ascii value :  974 symbol of ascii value  ascii valu0e :  ώ
number of ascii value :  975 symbol of ascii value  ascii valu0e :  Ϗ
number of ascii value :  976 symbol of ascii value  ascii valu0e :  ϐ
number of ascii value :  977 symbol of ascii value  ascii valu0e :  ϑ
number of ascii value :  978 symbol of ascii value  ascii valu0e :  ϒ
number of ascii value :  979 symbol of ascii value  ascii valu0e :  ϓ
number of ascii value :  980 symbol of ascii value  ascii valu0e :  ϔ
number of ascii value :  981 symbol of ascii value  ascii valu0e :  ϕ
number of ascii value :  982 symbol of ascii value  ascii valu0e :  ϖ
number of ascii value :  983 symbol of ascii value  ascii valu0e :  ϗ
number of ascii value :  984 symbol of ascii value  ascii valu0e :  Ϙ
number of ascii value :  985 symbol of ascii value  ascii valu0e :  ϙ
number of ascii value :  986 symbol of ascii value  ascii valu0e :  Ϛ
number of ascii value :  987 symbol of ascii value  ascii valu0e :  ϛ
number of ascii value :  988 symbol of ascii value  ascii valu0e :  Ϝ
number of ascii value :  989 symbol of ascii value  ascii valu0e :  ϝ
number of ascii value :  990 symbol of ascii value  ascii valu0e :  Ϟ
number of ascii value :  991 symbol of ascii value  ascii valu0e :  ϟ
number of ascii value :  992 symbol of ascii value  ascii valu0e :  Ϡ
number of ascii value :  993 symbol of ascii value  ascii valu0e :  ϡ
number of ascii value :  994 symbol of ascii value  ascii valu0e :  Ϣ
number of ascii value :  995 symbol of ascii value  ascii valu0e :  ϣ
number of ascii value :  996 symbol of ascii value  ascii valu0e :  Ϥ
number of ascii value :  997 symbol of ascii value  ascii valu0e :  ϥ
number of ascii value :  998 symbol of ascii value  ascii valu0e :  Ϧ
number of ascii value :  999 symbol of ascii value  ascii valu0e :  ϧ



'''