from tkinter import *
from tkinter import messagebox as ms
from pymysql import *
con=connect(db="nitish",user="root",password="root",host="localhost")
cur=con.cursor()	
root=Tk()
root.geometry('500x500')
root.title("Registration Form")
def add():
	cur.execute("insert into data values('%s','%s','%s','%s','%s')"%(entry_1.get(),entry_2.get(),entry_3.get(),entry_4.get(),entry_5.get()))
	con.commit()
	print("Record Inserted")
	ms.showinfo("Submit","Registered")
def show():
	global entry_6
	r=Tk()
	r.geometry('250x250')
	label_3=Label(r,text="User Name",width=20,font=("bold",10))
	label_3.place(x=40,y=50)
	entry_6=Entry(r)
	entry_6.place(x=40,y=100)
	Button(r,text='Display',width=20,bg='brown',fg='white',command=display).place(x=80,y=130)
def display():	
	cur.execute("Select * from data where uname='%s'"%entry_6.get())
	result=cur.fetchone()
	ro=Tk()
	label_3=Label(ro,text="First Name : "+result[0],font=("bold",10))
	label_3.place(x=40,y=50)
	print(result)
label_0=Label(root,text="Registration Form",width=20,font=("bold",20))
label_0.place(x=90,y=53)
label_1=Label(root,text="First Name",width=20,font=("bold",10))
label_1.place(x=80,y=130)
entry_1=Entry(root)
entry_1.place(x=240,y=130)
label_2=Label(root,text="Last Name",width=20,font=("bold",10))
label_2.place(x=68,y=180)
entry_2=Entry(root)
entry_2.place(x=240,y=180)
label_3=Label(root,text="User Name",width=20,font=("bold",10))
label_3.place(x=68,y=230)
entry_3=Entry(root)
entry_3.place(x=240,y=230)
label_4=Label(root,text="Email",width=20,font=("bold",10))
label_4.place(x=68,y=280)
entry_4=Entry(root)
entry_4.place(x=240,y=280)
label_5=Label(root,text="Password",width=20,font=("bold",10))
label_5.place(x=68,y=330)
entry_5=Entry(root)
entry_5.place(x=240,y=330)
Button(root,text='Submit',width=20,bg='brown',fg='white',command=add).place(x=270,y=380)
Button(root,text='Show',width=20,bg='brown',fg='white',command=show).place(x=270,y=440)
root.mainloop()
con.close()